### ISSUE TITLE
laravel 5.5 and above 

### ISSUE THREAD

**Issue by ghost** [junityco/laravel-nowsms#2]
failing ro intall on laravel 5.5

  Problem 1
    - Installation request for junityco/laravel-nowsms ^1.0 -> satisfiable by ju
nityco/laravel-nowsms[1.0].
    - junityco/laravel-nowsms 1.0 requires illuminate/notifications 5.3.* || 5.4
.* -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.3.0, v5.3
.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.
9] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by vgladimir** [comment]
Run the `composer update` command it will update the package to version `1.1` with Laravel 5.5 support.

**Comment by ghost** [comment]
installation succeeded thank you..
 nic>composer require junityco/laravel-nowsms
Using version ^1.1 for junityco/laravel-nowsms
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.0): Loading from cache
  - Installing junityco/laravel-nowsms (1.1): Loading from cache
Writing lock file
Generating optimized autoload files
